/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homeScreen;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kolsu
 */
public class adminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    CardLayout cardLayout;
    private Databaseconn databaseconn;
    private Backend backend;
    private ArrayList<Tiffins> tiffins;

    private ArrayList<Order> orders;


    private ArrayList<Users> users;

    private DefaultTableModel model = new DefaultTableModel();

    public adminDashboard() {
        initComponents();
        cardLayout = (CardLayout) (mainPanel.getLayout());
        databaseconn = new Databaseconn();
        backend = new Backend();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        priceInput6 = new javax.swing.JTextField();
        navbar = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        tiffinsBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        noOfTiffins = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        incomeLifetime1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        tiffinSoldLifetime1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        avgRatingLifetime1 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        incomeToday1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        tiffinSoldToday1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        avgRatingToday1 = new javax.swing.JLabel();
        tiffinPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userSignInButton = new javax.swing.JButton();
        idInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        rotiInput = new javax.swing.JTextField();
        sabjiInput = new javax.swing.JTextField();
        riceInput = new javax.swing.JTextField();
        papadInput = new javax.swing.JTextField();
        dalInput = new javax.swing.JTextField();
        sweetInput = new javax.swing.JTextField();
        priceInput = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        ordersPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        curdOrders = new javax.swing.JLabel();
        orderSubmitBtn = new javax.swing.JButton();
        orderDeleteBtn = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        statusLabel1 = new javax.swing.JLabel();
        orderIdInput = new javax.swing.JTextField();
        orderComboBox = new javax.swing.JComboBox<>();
        usersPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        userIdInput = new javax.swing.JTextField();
        userDeleteBtn = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        priceInput6.setBackground(java.awt.Color.white);
        priceInput6.setForeground(new java.awt.Color(23, 23, 29));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("dashboard"); // NOI18N

        navbar.setBackground(new java.awt.Color(51, 142, 218));
        navbar.setPreferredSize(new java.awt.Dimension(1200, 50));

        homeBtn.setText("HOME");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        tiffinsBtn.setText("TIFFINS");
        tiffinsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiffinsBtnActionPerformed(evt);
            }
        });

        orderBtn.setText("ORDERS");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderBtnActionPerformed(evt);
            }
        });

        userBtn.setText("USERS");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(homeBtn)
                .addGap(18, 18, 18)
                .addComponent(tiffinsBtn)
                .addGap(18, 18, 18)
                .addComponent(orderBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tiffinsBtn)
                    .addComponent(homeBtn)
                    .addComponent(orderBtn)
                    .addComponent(userBtn))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(23, 23, 29));
        mainPanel.setPreferredSize(new java.awt.Dimension(1200, 550));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(23, 23, 29));
        homePanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                homePanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        noOfTiffins.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        noOfTiffins.setForeground(java.awt.Color.white);
        noOfTiffins.setText("Currently serving 7 types of Tiffins");

        jPanel8.setBackground(new java.awt.Color(76, 80, 82));
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 150));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setText("Total Income Lifetime");

        incomeLifetime1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        incomeLifetime1.setForeground(java.awt.Color.white);
        incomeLifetime1.setText("₹ 15492");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel22))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(incomeLifetime1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(37, 37, 37)
                .addComponent(incomeLifetime1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(76, 80, 82));
        jPanel9.setPreferredSize(new java.awt.Dimension(300, 150));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setText("Total Tiffins Sold Lifetime");

        tiffinSoldLifetime1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tiffinSoldLifetime1.setForeground(java.awt.Color.white);
        tiffinSoldLifetime1.setText("77");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(61, 61, 61))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(tiffinSoldLifetime1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(40, 40, 40)
                .addComponent(tiffinSoldLifetime1)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(76, 80, 82));
        jPanel10.setPreferredSize(new java.awt.Dimension(300, 150));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setText("Average Rating Lifetime");

        avgRatingLifetime1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        avgRatingLifetime1.setForeground(java.awt.Color.white);
        avgRatingLifetime1.setText("4.5");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel24))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(avgRatingLifetime1)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addGap(37, 37, 37)
                .addComponent(avgRatingLifetime1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(76, 80, 82));
        jPanel11.setPreferredSize(new java.awt.Dimension(250, 150));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setText("Total Income Today");

        incomeToday1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        incomeToday1.setForeground(java.awt.Color.white);
        incomeToday1.setText("₹ 1800");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel25))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(incomeToday1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGap(37, 37, 37)
                .addComponent(incomeToday1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(76, 80, 82));
        jPanel12.setPreferredSize(new java.awt.Dimension(250, 150));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(java.awt.Color.white);
        jLabel26.setText("Total Tiffins Sold Today");

        tiffinSoldToday1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tiffinSoldToday1.setForeground(java.awt.Color.white);
        tiffinSoldToday1.setText("09");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addGap(66, 66, 66))
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(tiffinSoldToday1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(129, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(tiffinSoldToday1)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        jPanel13.setBackground(new java.awt.Color(76, 80, 82));
        jPanel13.setPreferredSize(new java.awt.Dimension(250, 150));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(java.awt.Color.white);
        jLabel27.setText("Average Rating Today");

        avgRatingToday1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        avgRatingToday1.setForeground(java.awt.Color.white);
        avgRatingToday1.setText("3.8");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel27)
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(avgRatingToday1)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(avgRatingToday1)
                    .addContainerGap(59, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homePanelLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noOfTiffins, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(127, 127, 127))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(noOfTiffins)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        mainPanel.add(homePanel, "card2");

        tiffinPanel.setBackground(new java.awt.Color(23, 23, 29));
        tiffinPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tiffinPanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tiffinPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tiffinPanelComponentShown(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Tiffin Dashboard");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Roti", "Sabji", "Rice", "Dal", "Pappad", "Sweet", "Price"
            }
        ));
        jTable1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTable1ComponentAdded(evt);
            }
        });
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("CURD TIFFINS");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("ID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Name");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Roti");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Sabji");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Rice");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Dal");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("Pappad");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("Sweet");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("Price");

        userSignInButton.setBackground(new java.awt.Color(23, 23, 29));
        userSignInButton.setForeground(new java.awt.Color(255, 255, 255));
        userSignInButton.setText("Submit");
        userSignInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        userSignInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userSignInButtonMouseClicked(evt);
            }
        });
        userSignInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSignInButtonActionPerformed(evt);
            }
        });

        idInput.setBackground(java.awt.Color.white);
        idInput.setForeground(new java.awt.Color(23, 23, 29));

        nameInput.setBackground(java.awt.Color.white);
        nameInput.setForeground(new java.awt.Color(23, 23, 29));

        rotiInput.setBackground(java.awt.Color.white);
        rotiInput.setForeground(new java.awt.Color(23, 23, 29));

        sabjiInput.setBackground(java.awt.Color.white);
        sabjiInput.setForeground(new java.awt.Color(23, 23, 29));

        riceInput.setBackground(java.awt.Color.white);
        riceInput.setForeground(new java.awt.Color(23, 23, 29));

        papadInput.setBackground(java.awt.Color.white);
        papadInput.setForeground(new java.awt.Color(23, 23, 29));

        dalInput.setBackground(java.awt.Color.white);
        dalInput.setForeground(new java.awt.Color(23, 23, 29));

        sweetInput.setBackground(java.awt.Color.white);
        sweetInput.setForeground(new java.awt.Color(23, 23, 29));

        priceInput.setBackground(java.awt.Color.white);
        priceInput.setForeground(new java.awt.Color(23, 23, 29));

        deleteBtn.setBackground(java.awt.Color.red);
        deleteBtn.setForeground(java.awt.Color.white);
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tiffinPanelLayout = new javax.swing.GroupLayout(tiffinPanel);
        tiffinPanel.setLayout(tiffinPanelLayout);
        tiffinPanelLayout.setHorizontalGroup(
            tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tiffinPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14)
                    .addGroup(tiffinPanelLayout.createSequentialGroup()
                        .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(tiffinPanelLayout.createSequentialGroup()
                                    .addComponent(idInput)
                                    .addGap(26, 26, 26))
                                .addGroup(tiffinPanelLayout.createSequentialGroup()
                                    .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(81, 81, 81)))
                            .addGroup(tiffinPanelLayout.createSequentialGroup()
                                .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rotiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sabjiInput, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceInput, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)))
                        .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(userSignInButton, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(sweetInput)
                            .addComponent(dalInput)
                            .addComponent(papadInput)
                            .addComponent(riceInput)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );
        tiffinPanelLayout.setVerticalGroup(
            tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tiffinPanelLayout.createSequentialGroup()
                .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tiffinPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6))
                        .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tiffinPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(riceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12))
                            .addGroup(tiffinPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel7)))
                        .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tiffinPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel11))
                            .addGroup(tiffinPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(papadInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rotiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dalInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tiffinPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sabjiInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sweetInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(tiffinPanelLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(62, 62, 62)))
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addGroup(tiffinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userSignInButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteBtn))
                    .addGroup(tiffinPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        mainPanel.add(tiffinPanel, "card3");

        ordersPanel.setBackground(new java.awt.Color(23, 23, 29));
        ordersPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ordersPanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Roti", "Sabji", "Rice", "Dal", "Pappad", "Sweet", "Price"
            }
        ));
        orderTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                orderTableComponentAdded(evt);
            }
        });
        orderTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                orderTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        orderTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(orderTable);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Orders Dashboard");

        curdOrders.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        curdOrders.setForeground(java.awt.Color.white);
        curdOrders.setText("CURD ORDERS");

        orderSubmitBtn.setBackground(new java.awt.Color(23, 23, 29));
        orderSubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        orderSubmitBtn.setText("Submit");
        orderSubmitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        orderSubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderSubmitBtnMouseClicked(evt);
            }
        });
        orderSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderSubmitBtnActionPerformed(evt);
            }
        });

        orderDeleteBtn.setBackground(java.awt.Color.red);
        orderDeleteBtn.setForeground(java.awt.Color.white);
        orderDeleteBtn.setText("Delete");
        orderDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderDeleteBtnActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idLabel.setForeground(java.awt.Color.white);
        idLabel.setText("Order ID");

        statusLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        statusLabel1.setForeground(java.awt.Color.white);
        statusLabel1.setText("Status");

        orderIdInput.setBackground(java.awt.Color.white);
        orderIdInput.setForeground(new java.awt.Color(23, 23, 29));

        orderComboBox.setBackground(java.awt.Color.white);
        orderComboBox.setForeground(new java.awt.Color(23, 23, 29));
        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order Placed", "Accepted", "Cooking", "Dispatched", "Delivered", "Rejected" }));

        javax.swing.GroupLayout ordersPanelLayout = new javax.swing.GroupLayout(ordersPanel);
        ordersPanel.setLayout(ordersPanelLayout);
        ordersPanelLayout.setHorizontalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idLabel)
                    .addComponent(orderIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(statusLabel1)
                    .addComponent(orderSubmitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderDeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(orderComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(879, Short.MAX_VALUE))
            .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ordersPanelLayout.createSequentialGroup()
                    .addGap(97, 97, 97)
                    .addComponent(curdOrders)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 379, Short.MAX_VALUE)
                    .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(97, 97, 97)))
        );
        ordersPanelLayout.setVerticalGroup(
            ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ordersPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(statusLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(orderSubmitBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderDeleteBtn)
                .addContainerGap(234, Short.MAX_VALUE))
            .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ordersPanelLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(ordersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(curdOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        mainPanel.add(ordersPanel, "card4");

        usersPanel.setBackground(new java.awt.Color(23, 23, 29));
        usersPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                usersPanelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        usersPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                usersPanelComponentShown(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("Users Dashboard");

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Roti", "Sabji", "Rice", "Dal", "Pappad", "Sweet", "Price"
            }
        ));
        usersTable.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                usersTableComponentAdded(evt);
            }
        });
        usersTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                usersTableAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(usersTable);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("CURD Users");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("ID");

        userIdInput.setBackground(java.awt.Color.white);
        userIdInput.setForeground(new java.awt.Color(23, 23, 29));

        userDeleteBtn.setBackground(java.awt.Color.red);
        userDeleteBtn.setForeground(java.awt.Color.white);
        userDeleteBtn.setText("Delete");
        userDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout usersPanelLayout = new javax.swing.GroupLayout(usersPanel);
        usersPanel.setLayout(usersPanelLayout);
        usersPanelLayout.setHorizontalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usersPanelLayout.createSequentialGroup()
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel16))
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(userDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
        );
        usersPanelLayout.setVerticalGroup(
            usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usersPanelLayout.createSequentialGroup()
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(usersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userDeleteBtn))
                    .addGroup(usersPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        mainPanel.add(usersPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:

        mainPanel.add("homePanel", homePanel);
        cardLayout.show(mainPanel, "homePanel");

    }//GEN-LAST:event_homeBtnActionPerformed

    private void tiffinsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiffinsBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.add("tiffinPanel", tiffinPanel);
        cardLayout.show(mainPanel, "tiffinPanel");

    }//GEN-LAST:event_tiffinsBtnActionPerformed

    private void orderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderBtnActionPerformed
        // TODO add your handling code here:

        mainPanel.add("ordersPanel", ordersPanel);
        cardLayout.show(mainPanel, "ordersPanel");
    }//GEN-LAST:event_orderBtnActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1AncestorAdded

    private void userSignInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userSignInButtonMouseClicked

    }//GEN-LAST:event_userSignInButtonMouseClicked

    private void userSignInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSignInButtonActionPerformed
        // TODO add your handling code here:

        Tiffins selectedTiffin = new Tiffins();

        selectedTiffin.id = Integer.parseInt(idInput.getText());
        selectedTiffin.name = nameInput.getText();

        selectedTiffin.roti = Integer.parseInt(rotiInput.getText());
        selectedTiffin.sabji = sabjiInput.getText();
        selectedTiffin.rice = Integer.parseInt(riceInput.getText());
        selectedTiffin.dal = dalInput.getText();
        selectedTiffin.pappad = Integer.parseInt(papadInput.getText());
        selectedTiffin.sweet = sweetInput.getText();
        selectedTiffin.price = Integer.parseInt(priceInput.getText());

        int result = backend.updateTiffin(selectedTiffin);
        if (result == 2) {
            JOptionPane.showMessageDialog(null, "Tiffin Didn't Exsist. Created New Tiffin.",
                    "INFORMATION",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (result == 0) {
            JOptionPane.showMessageDialog(null, "Tiffin Could Not Be Updated.",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Tiffin Updated Successfully.",
                    "INFORMATION",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_userSignInButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel) jTable1.getModel();
        Vector row = model.getDataVector().elementAt(jTable1.getSelectedRow());
        idInput.setText(row.get(0).toString());
        nameInput.setText(row.get(1).toString());
        rotiInput.setText(row.get(2).toString());
        sabjiInput.setText(row.get(3).toString());
        riceInput.setText(row.get(4).toString());
        dalInput.setText(row.get(5).toString());
        papadInput.setText(row.get(6).toString());
        sweetInput.setText(row.get(7).toString());
        priceInput.setText(row.get(8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTable1ComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jTable1ComponentAdded

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        Vector row = model.getDataVector().elementAt(jTable1.getSelectedRow());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would You Like to Delete " + row.get(1) + " Tiffin ?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            boolean result = backend.deleteTiffin((int) row.get(0));
            if (result == true) {
                JOptionPane.showMessageDialog(null, "Tiffin Deleted Succesfully",
                        "INFORMATION",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Tiffin Could Not Be Deleted",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void homePanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_homePanelAncestorAdded
        // TODO add your handling code here:

        noOfTiffins.setText("Currently Serving " + backend.getTiffinCount() + " types of Tiffins");
    }//GEN-LAST:event_homePanelAncestorAdded

    private void tiffinPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tiffinPanelAncestorAdded
        // TODO add your handling code here:
        tiffins = backend.getTiffins();
        model.setColumnIdentifiers(new Object[]{"ID", "NAME", "Roti", "Sabji", "Rice", "Dal", "Pappad", "Sweet", "Price"});
        jTable1.setModel(model);
        model.setRowCount(0);

        for (int i = 0; i < tiffins.size(); i++) {
            model.addRow(new Object[]{tiffins.get(i).id, tiffins.get(i).name, tiffins.get(i).roti, tiffins.get(i).sabji, tiffins.get(i).rice,
                tiffins.get(i).dal, tiffins.get(i).pappad, tiffins.get(i).sweet, tiffins.get(i).price});
        }
    }//GEN-LAST:event_tiffinPanelAncestorAdded

    private void tiffinPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tiffinPanelComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_tiffinPanelComponentShown

    private void orderTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_orderTableComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_orderTableComponentAdded

    private void orderTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_orderTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_orderTableAncestorAdded

    private void orderTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderTableMouseClicked
        // TODO add your handling code here:

        model = (DefaultTableModel) orderTable.getModel();
        Vector row = model.getDataVector().elementAt(orderTable.getSelectedRow());

        orderIdInput.setText(row.get(0).toString());
        orderComboBox.setSelectedItem(row.get(4).toString());

    }//GEN-LAST:event_orderTableMouseClicked

    private void orderSubmitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderSubmitBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_orderSubmitBtnMouseClicked

    private void orderSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderSubmitBtnActionPerformed
        // TODO add your handling code here:
        int result = backend.setOrderStatus(Integer.parseInt(orderIdInput.getText()), String.valueOf(orderComboBox.getSelectedItem()));
        if (result == 0) {
            JOptionPane.showMessageDialog(null, "Order Does Not Exsist.",
                    "INFORMATION",
                    JOptionPane.INFORMATION_MESSAGE);
        } else if (result == -1) {
            JOptionPane.showMessageDialog(null, "Order Could Not Be Updated.",
                    "ERROR",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Order Updated Successfully.",
                    "INFORMATION",
                    JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_orderSubmitBtnActionPerformed

    private void orderDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderDeleteBtnActionPerformed
        // TODO add your handling code here:

        Vector row = model.getDataVector().elementAt(orderTable.getSelectedRow());
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would You Like to Delete Order " + row.get(0) + " ?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            int result;
            try {
                result = backend.deleteOrder((int) row.get(0));

                if (result == -1) {
                    JOptionPane.showMessageDialog(this, "Order Does Not Exsist.",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Order Deleted Succesfully",
                            "INFORMATION",
                            JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (Exception ex) {
                Logger.getLogger(adminDashboard.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Something went wrong!",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_orderDeleteBtnActionPerformed

    private void ordersPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ordersPanelAncestorAdded
        // TODO add your handling code here:

        orders = backend.getOrders();
        model.setColumnIdentifiers(new Object[]{"Order ID", "User ID", "Tiffin ID", "Tiffin Price", "Status", "Rating"});
        orderTable.setModel(model);
        model.setRowCount(0);

        for (int i = 0; i < orders.size(); i++) {
            model.addRow(new Object[]{orders.get(i).oid, orders.get(i).uid, orders.get(i).tid,
                orders.get(i).price, orders.get(i).status,
                orders.get(i).rating});
        }
    }//GEN-LAST:event_ordersPanelAncestorAdded

    private void usersTableComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_usersTableComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_usersTableComponentAdded

    private void usersTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_usersTableAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_usersTableAncestorAdded

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        // TODO add your handling code here:
        Vector row = model.getDataVector().elementAt(usersTable.getSelectedRow());
        userIdInput.setText(row.get(0).toString());

    }//GEN-LAST:event_usersTableMouseClicked

    private void userDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeleteBtnActionPerformed
        // TODO add your handling code here:
        Vector row = model.getDataVector().elementAt(usersTable.getSelectedRow());

        int dialogResult = JOptionPane.showConfirmDialog(null, "Would You Like to Delete User " + row.get(0) + " ?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            int result;
            try {
                result = backend.deleteUser(Integer.parseInt(userIdInput.getText()));

                if (result == -1) {
                    JOptionPane.showMessageDialog(this, "User Does Not Exsist.",
                            "ERROR", JOptionPane.ERROR_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "User Deleted Succesfully",
                            "INFORMATION",
                            JOptionPane.INFORMATION_MESSAGE);
                }

            } catch (Exception ex) {
                Logger.getLogger(adminDashboard.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Something went wrong!",
                        "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_userDeleteBtnActionPerformed

    private void usersPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_usersPanelAncestorAdded
        // TODO add your handling code here:
        users = backend.getAllUsers();
        model.setColumnIdentifiers(new Object[]{"User ID", "Name", "Email", "Phone Number", "Tiffins Ordered", "Total Bill Amount"});
        usersTable.setModel(model);
        model.setRowCount(0);

        for (int i = 0; i < users.size(); i++) {
            model.addRow(new Object[]{users.get(i).id, users.get(i).firstName + users.get(i).lastName,
                users.get(i).email,
                users.get(i).phoneNumber, backend.getUserOrderCount(users.get(i).id),
                backend.getUserTotalBill(users.get(i).id)});
        }
    }//GEN-LAST:event_usersPanelAncestorAdded

    private void usersPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_usersPanelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_usersPanelComponentShown

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        // TODO add your handling code here:
        mainPanel.add("usersPanel", usersPanel);
        cardLayout.show(mainPanel, "usersPanel");

    }//GEN-LAST:event_userBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avgRatingLifetime1;
    private javax.swing.JLabel avgRatingToday1;
    private javax.swing.JLabel curdOrders;
    private javax.swing.JTextField dalInput;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel incomeLifetime1;
    private javax.swing.JLabel incomeToday1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField nameInput;
    private javax.swing.JPanel navbar;
    private javax.swing.JLabel noOfTiffins;
    private javax.swing.JButton orderBtn;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JButton orderDeleteBtn;
    private javax.swing.JTextField orderIdInput;
    private javax.swing.JButton orderSubmitBtn;
    private javax.swing.JTable orderTable;
    private javax.swing.JPanel ordersPanel;
    private javax.swing.JTextField papadInput;
    private javax.swing.JTextField priceInput;
    private javax.swing.JTextField priceInput6;
    private javax.swing.JTextField riceInput;
    private javax.swing.JTextField rotiInput;
    private javax.swing.JTextField sabjiInput;
    private javax.swing.JLabel statusLabel1;
    private javax.swing.JTextField sweetInput;
    private javax.swing.JPanel tiffinPanel;
    private javax.swing.JLabel tiffinSoldLifetime1;
    private javax.swing.JLabel tiffinSoldToday1;
    private javax.swing.JButton tiffinsBtn;
    private javax.swing.JButton userBtn;
    private javax.swing.JButton userDeleteBtn;
    private javax.swing.JTextField userIdInput;
    private javax.swing.JButton userSignInButton;
    private javax.swing.JPanel usersPanel;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
